CLOUDINARY_API_KEY: 235919889851883
BEGIN;
--
-- Create model Subject
--
CREATE TABLE "userapp_subject" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL);
--
-- Create model User
--
CREATE TABLE "userapp_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "name" varchar(255) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "phone" varchar(15) NOT NULL, "is_active" boolean NOT NULL, "is_staff" boolean NOT NULL, "is_mentor" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "otp" varchar(6) NULL, "otp_created_at" timestamp with time zone NULL, "is_verified" boolean NOT NULL, "bio" text NULL, "experience" integer NOT NULL);
CREATE TABLE "userapp_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "userapp_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE TABLE "userapp_user_subjects" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "subject_id" bigint NOT NULL);
--
-- Create model FocusBuddySession
--
CREATE TABLE "userapp_focusbuddysession" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NULL, "session_type" varchar(10) NOT NULL, "status" varchar(15) NOT NULL, "duration_minutes" integer NOT NULL, "max_participants" integer NOT NULL, "started_at" timestamp with time zone NOT NULL, "ends_at" timestamp with time zone NOT NULL, "ended_at" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "creator_id" bigint NOT NULL);
--
-- Create model FocusBuddyParticipant
--
CREATE TABLE "userapp_focusbuddyparticipant" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "joined_at" timestamp with time zone NOT NULL, "left_at" timestamp with time zone NULL, "camera_enabled" boolean NOT NULL, "microphone_enabled" boolean NOT NULL, "user_id" bigint NOT NULL, "session_id" bigint NOT NULL);
--
-- Create model FocusBuddyMessage
--
CREATE TABLE "userapp_focusbuddymessage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "message" text NOT NULL, "is_system_message" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "sender_id" bigint NOT NULL, "session_id" bigint NOT NULL);
--
-- Create model FocusBuddyStats
--
CREATE TABLE "userapp_focusbuddystats" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "total_sessions_joined" integer NOT NULL, "total_sessions_created" integer NOT NULL, "completed_sessions" integer NOT NULL, "total_focus_minutes" integer NOT NULL, "average_session_rating" numeric(3, 2) NOT NULL, "total_ratings_given" integer NOT NULL, "current_streak" integer NOT NULL, "longest_streak" integer NOT NULL, "last_session_date" date NULL, "preferred_duration" integer NOT NULL, "preferred_session_type" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Journal
--
CREATE TABLE "userapp_journal" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "mood" varchar(20) NOT NULL, "description" text NOT NULL, "date" date NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_blocked" boolean NOT NULL, "user_id" bigint NOT NULL);
--
-- Create model Mentor
--
CREATE TABLE "userapp_mentor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "profile_image" varchar(255) NULL, "expertise_level" varchar(20) NOT NULL, "hourly_rate" numeric(10, 2) NOT NULL, "availability" jsonb NOT NULL, "rating" numeric(3, 2) NOT NULL, "total_sessions" integer NOT NULL, "total_students" integer NOT NULL, "is_available" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_approved" boolean NOT NULL, "approval_status" varchar(20) NOT NULL, "submitted_for_approval" boolean NOT NULL, "submitted_at" timestamp with time zone NULL, "approved_at" timestamp with time zone NULL, "approved_by_id" bigint NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model MentorApprovalRequest
--
CREATE TABLE "userapp_mentorapprovalrequest" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "requested_at" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "admin_notes" text NULL, "processed_at" timestamp with time zone NULL, "mentor_id" bigint NOT NULL, "processed_by_id" bigint NULL);
--
-- Create model MentorSession
--
CREATE TABLE "userapp_mentorsession" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "scheduled_date" date NOT NULL, "scheduled_time" time NOT NULL, "duration_minutes" integer NOT NULL, "session_mode" varchar(10) NOT NULL, "status" varchar(15) NOT NULL, "meeting_link" varchar(200) NULL, "meeting_id" varchar(100) NULL, "meeting_password" varchar(50) NULL, "session_notes" text NULL, "student_feedback" text NULL, "mentor_feedback" text NULL, "student_rating" integer NULL, "mentor_rating" integer NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "confirmed_at" timestamp with time zone NULL, "started_at" timestamp with time zone NULL, "ended_at" timestamp with time zone NULL, "cancelled_at" timestamp with time zone NULL, "cancellation_reason" text NULL, "cancelled_by_id" bigint NULL, "mentor_id" bigint NOT NULL, "student_id" bigint NOT NULL);
CREATE TABLE "userapp_mentorsession_subjects" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "mentorsession_id" bigint NOT NULL, "subject_id" bigint NOT NULL);
--
-- Create model MentorEarnings
--
CREATE TABLE "userapp_mentorearnings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "session_amount" numeric(10, 2) NOT NULL, "platform_commission" numeric(10, 2) NOT NULL, "mentor_earning" numeric(10, 2) NOT NULL, "payout_status" varchar(20) NOT NULL, "payout_date" timestamp with time zone NULL, "payout_reference" varchar(100) NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "mentor_id" bigint NOT NULL, "session_id" bigint NOT NULL);
--
-- Create model PomodoroSettings
--
CREATE TABLE "userapp_pomodorosettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "focus_duration" integer NOT NULL, "short_break_duration" integer NOT NULL, "long_break_duration" integer NOT NULL, "sessions_before_long_break" integer NOT NULL, "auto_start_next_session" boolean NOT NULL, "play_sound_when_session_ends" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model SessionMessage
--
CREATE TABLE "userapp_sessionmessage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "message" text NOT NULL, "is_system_message" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "sender_id" bigint NOT NULL, "session_id" bigint NOT NULL);
--
-- Create model SessionPayment
--
CREATE TABLE "userapp_sessionpayment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "amount" numeric(10, 2) NOT NULL, "currency" varchar(3) NOT NULL, "payment_method" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "transaction_id" varchar(100) NULL, "gateway_payment_id" varchar(100) NULL, "gateway_order_id" varchar(100) NULL, "gateway_signature" varchar(200) NULL, "base_amount" numeric(10, 2) NOT NULL, "platform_fee" numeric(10, 2) NOT NULL, "tax_amount" numeric(10, 2) NOT NULL, "discount_amount" numeric(10, 2) NOT NULL, "refund_amount" numeric(10, 2) NOT NULL, "refund_reason" text NULL, "refunded_at" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "paid_at" timestamp with time zone NULL, "gateway_response" jsonb NULL, "session_id" bigint NOT NULL UNIQUE);
--
-- Create model Task
--
CREATE TABLE "userapp_task" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "description" text NULL, "estimated_minutes" integer NOT NULL, "estimated_pomodoros" integer NOT NULL, "completed_pomodoros" integer NOT NULL, "is_completed" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL);
--
-- Create model PomodoroSession
--
CREATE TABLE "userapp_pomodorosession" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "session_type" varchar(20) NOT NULL, "start_time" timestamp with time zone NOT NULL, "end_time" timestamp with time zone NULL, "duration_minutes" integer NOT NULL, "is_completed" boolean NOT NULL, "task_id" bigint NOT NULL);
--
-- Create model FocusBuddyFeedback
--
CREATE TABLE "userapp_focusbuddyfeedback" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "session_rating" integer NOT NULL, "feedback_text" text NULL, "would_join_again" boolean NOT NULL, "session_helpful" boolean NOT NULL, "good_environment" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "participant_id" bigint NOT NULL, "session_id" bigint NOT NULL);
--
-- Create model SessionReview
--
CREATE TABLE "userapp_sessionreview" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rating" integer NOT NULL, "review_text" text NOT NULL, "is_public" boolean NOT NULL, "is_verified" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "reviewer_id" bigint NOT NULL, "session_id" bigint NOT NULL UNIQUE);
CREATE INDEX "userapp_user_email_f366e595_like" ON "userapp_user" ("email" varchar_pattern_ops);
ALTER TABLE "userapp_user_groups" ADD CONSTRAINT "userapp_user_groups_user_id_group_id_809fade4_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "userapp_user_groups" ADD CONSTRAINT "userapp_user_groups_user_id_1f2cef9b_fk_userapp_user_id" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_user_groups" ADD CONSTRAINT "userapp_user_groups_group_id_2c7413e1_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_user_groups_user_id_1f2cef9b" ON "userapp_user_groups" ("user_id");
CREATE INDEX "userapp_user_groups_group_id_2c7413e1" ON "userapp_user_groups" ("group_id");
ALTER TABLE "userapp_user_user_permissions" ADD CONSTRAINT "userapp_user_user_permis_user_id_permission_id_2e646fa8_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "userapp_user_user_permissions" ADD CONSTRAINT "userapp_user_user_pe_user_id_83c73166_fk_userapp_u" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_user_user_permissions" ADD CONSTRAINT "userapp_user_user_pe_permission_id_d925323f_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_user_user_permissions_user_id_83c73166" ON "userapp_user_user_permissions" ("user_id");
CREATE INDEX "userapp_user_user_permissions_permission_id_d925323f" ON "userapp_user_user_permissions" ("permission_id");
ALTER TABLE "userapp_user_subjects" ADD CONSTRAINT "userapp_user_subjects_user_id_subject_id_0fe80032_uniq" UNIQUE ("user_id", "subject_id");
ALTER TABLE "userapp_user_subjects" ADD CONSTRAINT "userapp_user_subjects_user_id_ffcd6be3_fk_userapp_user_id" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_user_subjects" ADD CONSTRAINT "userapp_user_subjects_subject_id_faa08009_fk_userapp_subject_id" FOREIGN KEY ("subject_id") REFERENCES "userapp_subject" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_user_subjects_user_id_ffcd6be3" ON "userapp_user_subjects" ("user_id");
CREATE INDEX "userapp_user_subjects_subject_id_faa08009" ON "userapp_user_subjects" ("subject_id");
ALTER TABLE "userapp_focusbuddysession" ADD CONSTRAINT "userapp_focusbuddyse_creator_id_f8ac871b_fk_userapp_u" FOREIGN KEY ("creator_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_focusbuddysession_creator_id_f8ac871b" ON "userapp_focusbuddysession" ("creator_id");
ALTER TABLE "userapp_focusbuddyparticipant" ADD CONSTRAINT "userapp_focusbuddyparticipant_session_id_user_id_da947e5c_uniq" UNIQUE ("session_id", "user_id");
ALTER TABLE "userapp_focusbuddyparticipant" ADD CONSTRAINT "userapp_focusbuddypa_user_id_a3f65aef_fk_userapp_u" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_focusbuddyparticipant" ADD CONSTRAINT "userapp_focusbuddypa_session_id_3500eca1_fk_userapp_f" FOREIGN KEY ("session_id") REFERENCES "userapp_focusbuddysession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_focusbuddyparticipant_user_id_a3f65aef" ON "userapp_focusbuddyparticipant" ("user_id");
CREATE INDEX "userapp_focusbuddyparticipant_session_id_3500eca1" ON "userapp_focusbuddyparticipant" ("session_id");
ALTER TABLE "userapp_focusbuddymessage" ADD CONSTRAINT "userapp_focusbuddymessage_sender_id_e9d67d3f_fk_userapp_user_id" FOREIGN KEY ("sender_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_focusbuddymessage" ADD CONSTRAINT "userapp_focusbuddyme_session_id_0ae2cf07_fk_userapp_f" FOREIGN KEY ("session_id") REFERENCES "userapp_focusbuddysession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_focusbuddymessage_sender_id_e9d67d3f" ON "userapp_focusbuddymessage" ("sender_id");
CREATE INDEX "userapp_focusbuddymessage_session_id_0ae2cf07" ON "userapp_focusbuddymessage" ("session_id");
ALTER TABLE "userapp_focusbuddystats" ADD CONSTRAINT "userapp_focusbuddystats_user_id_328dd3a9_fk_userapp_user_id" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_journal" ADD CONSTRAINT "userapp_journal_user_id_a80df964_fk_userapp_user_id" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_journal_user_id_a80df964" ON "userapp_journal" ("user_id");
ALTER TABLE "userapp_mentor" ADD CONSTRAINT "userapp_mentor_approved_by_id_e4cc84dd_fk_userapp_user_id" FOREIGN KEY ("approved_by_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_mentor" ADD CONSTRAINT "userapp_mentor_user_id_844da445_fk_userapp_user_id" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_mentor_approved_by_id_e4cc84dd" ON "userapp_mentor" ("approved_by_id");
ALTER TABLE "userapp_mentorapprovalrequest" ADD CONSTRAINT "userapp_mentorapprov_mentor_id_3af46ef4_fk_userapp_m" FOREIGN KEY ("mentor_id") REFERENCES "userapp_mentor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_mentorapprovalrequest" ADD CONSTRAINT "userapp_mentorapprov_processed_by_id_6866eff6_fk_userapp_u" FOREIGN KEY ("processed_by_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_mentorapprovalrequest_mentor_id_3af46ef4" ON "userapp_mentorapprovalrequest" ("mentor_id");
CREATE INDEX "userapp_mentorapprovalrequest_processed_by_id_6866eff6" ON "userapp_mentorapprovalrequest" ("processed_by_id");
ALTER TABLE "userapp_mentorsession" ADD CONSTRAINT "userapp_mentorsession_mentor_id_scheduled_date_255c887a_uniq" UNIQUE ("mentor_id", "scheduled_date", "scheduled_time");
ALTER TABLE "userapp_mentorsession" ADD CONSTRAINT "userapp_mentorsessio_cancelled_by_id_9cb9122f_fk_userapp_u" FOREIGN KEY ("cancelled_by_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_mentorsession" ADD CONSTRAINT "userapp_mentorsession_mentor_id_8fc4dc7b_fk_userapp_mentor_id" FOREIGN KEY ("mentor_id") REFERENCES "userapp_mentor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_mentorsession" ADD CONSTRAINT "userapp_mentorsession_student_id_c843d76d_fk_userapp_user_id" FOREIGN KEY ("student_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_mentorsession_cancelled_by_id_9cb9122f" ON "userapp_mentorsession" ("cancelled_by_id");
CREATE INDEX "userapp_mentorsession_mentor_id_8fc4dc7b" ON "userapp_mentorsession" ("mentor_id");
CREATE INDEX "userapp_mentorsession_student_id_c843d76d" ON "userapp_mentorsession" ("student_id");
ALTER TABLE "userapp_mentorsession_subjects" ADD CONSTRAINT "userapp_mentorsession_su_mentorsession_id_subject_53f333e3_uniq" UNIQUE ("mentorsession_id", "subject_id");
ALTER TABLE "userapp_mentorsession_subjects" ADD CONSTRAINT "userapp_mentorsessio_mentorsession_id_bef23cc1_fk_userapp_m" FOREIGN KEY ("mentorsession_id") REFERENCES "userapp_mentorsession" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_mentorsession_subjects" ADD CONSTRAINT "userapp_mentorsessio_subject_id_c30cbf62_fk_userapp_s" FOREIGN KEY ("subject_id") REFERENCES "userapp_subject" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_mentorsession_subjects_mentorsession_id_bef23cc1" ON "userapp_mentorsession_subjects" ("mentorsession_id");
CREATE INDEX "userapp_mentorsession_subjects_subject_id_c30cbf62" ON "userapp_mentorsession_subjects" ("subject_id");
ALTER TABLE "userapp_mentorearnings" ADD CONSTRAINT "userapp_mentorearnings_mentor_id_bff2ccaf_fk_userapp_mentor_id" FOREIGN KEY ("mentor_id") REFERENCES "userapp_mentor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_mentorearnings" ADD CONSTRAINT "userapp_mentorearnin_session_id_0af821c0_fk_userapp_m" FOREIGN KEY ("session_id") REFERENCES "userapp_mentorsession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_mentorearnings_mentor_id_bff2ccaf" ON "userapp_mentorearnings" ("mentor_id");
CREATE INDEX "userapp_mentorearnings_session_id_0af821c0" ON "userapp_mentorearnings" ("session_id");
ALTER TABLE "userapp_pomodorosettings" ADD CONSTRAINT "userapp_pomodorosettings_user_id_93e32010_fk_userapp_user_id" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_sessionmessage" ADD CONSTRAINT "userapp_sessionmessage_sender_id_da73f045_fk_userapp_user_id" FOREIGN KEY ("sender_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_sessionmessage" ADD CONSTRAINT "userapp_sessionmessa_session_id_6500001f_fk_userapp_m" FOREIGN KEY ("session_id") REFERENCES "userapp_mentorsession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_sessionmessage_sender_id_da73f045" ON "userapp_sessionmessage" ("sender_id");
CREATE INDEX "userapp_sessionmessage_session_id_6500001f" ON "userapp_sessionmessage" ("session_id");
ALTER TABLE "userapp_sessionpayment" ADD CONSTRAINT "userapp_sessionpayme_session_id_40f5b2b4_fk_userapp_m" FOREIGN KEY ("session_id") REFERENCES "userapp_mentorsession" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_task" ADD CONSTRAINT "userapp_task_user_id_3bc4367e_fk_userapp_user_id" FOREIGN KEY ("user_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_task_user_id_3bc4367e" ON "userapp_task" ("user_id");
ALTER TABLE "userapp_pomodorosession" ADD CONSTRAINT "userapp_pomodorosession_task_id_ffa0095c_fk_userapp_task_id" FOREIGN KEY ("task_id") REFERENCES "userapp_task" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_pomodorosession_task_id_ffa0095c" ON "userapp_pomodorosession" ("task_id");
ALTER TABLE "userapp_focusbuddyfeedback" ADD CONSTRAINT "userapp_focusbuddyfeedba_session_id_participant_i_afe5c3ce_uniq" UNIQUE ("session_id", "participant_id");
ALTER TABLE "userapp_focusbuddyfeedback" ADD CONSTRAINT "userapp_focusbuddyfe_participant_id_e8d3f5c8_fk_userapp_f" FOREIGN KEY ("participant_id") REFERENCES "userapp_focusbuddyparticipant" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_focusbuddyfeedback" ADD CONSTRAINT "userapp_focusbuddyfe_session_id_21836043_fk_userapp_f" FOREIGN KEY ("session_id") REFERENCES "userapp_focusbuddysession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_focusbuddyfeedback_participant_id_e8d3f5c8" ON "userapp_focusbuddyfeedback" ("participant_id");
CREATE INDEX "userapp_focusbuddyfeedback_session_id_21836043" ON "userapp_focusbuddyfeedback" ("session_id");
ALTER TABLE "userapp_sessionreview" ADD CONSTRAINT "userapp_sessionreview_session_id_reviewer_id_10d42cec_uniq" UNIQUE ("session_id", "reviewer_id");
ALTER TABLE "userapp_sessionreview" ADD CONSTRAINT "userapp_sessionreview_reviewer_id_e98200ec_fk_userapp_user_id" FOREIGN KEY ("reviewer_id") REFERENCES "userapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "userapp_sessionreview" ADD CONSTRAINT "userapp_sessionrevie_session_id_3c4d9021_fk_userapp_m" FOREIGN KEY ("session_id") REFERENCES "userapp_mentorsession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "userapp_sessionreview_reviewer_id_e98200ec" ON "userapp_sessionreview" ("reviewer_id");
COMMIT;
