# Generated by Django 5.2 on 2025-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusbuddysession',
            name='session_type',
            field=models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('reading', 'Reading')], default='video', max_length=10),
        ),
        migrations.AlterField(
            model_name='focusbuddystats',
            name='preferred_session_type',
            field=models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('reading', 'Reading')], default='video', max_length=10),
        ),
    ]
