# Generated by Django 5.2 on 2025-06-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_focusbuddysession_session_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusbuddysession',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
