# Generated by Django 5.2 on 2025-06-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_creator_focusbuddysession_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
