# Generated by Django 5.2 on 2025-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_mentor_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
