# Generated by Django 5.2 on 2025-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_mentorsession_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
