# Generated by Django 5.2 on 2025-07-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_sessionreview_review_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-rating']},
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='total_sessions',
        ),
    ]
