# Generated by Django 5.2 on 2025-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_mentor_options_remove_mentor_total_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
