# Generated by Django 5.2 on 2025-07-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_task_estimated_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosettings',
            name='long_break_duration',
        ),
        migrations.RemoveField(
            model_name='pomodorosettings',
            name='sessions_before_long_break',
        ),
        migrations.RemoveField(
            model_name='pomodorosettings',
            name='short_break_duration',
        ),
    ]
