# Generated by Django 5.2 on 2025-05-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_mentor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='expertise_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20),
        ),
    ]
