# Generated by Django 5.2 on 2025-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_mentor_expertise_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
