# Generated by Django 5.2 on 2025-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_mentor_wallet_balance_user_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusbuddyparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
