# Generated by Django 5.2 on 2025-06-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_mentorsession_mentorearnings_sessionmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionreview',
            name='communication_rating',
        ),
        migrations.RemoveField(
            model_name='sessionreview',
            name='helpfulness_rating',
        ),
        migrations.RemoveField(
            model_name='sessionreview',
            name='knowledge_rating',
        ),
    ]
