# Generated by Django 5.2.4 on 2025-07-11 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_mentorreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorreport',
            unique_together={('reporter', 'mentor')},
        ),
        migrations.AlterField(
            model_name='mentorreport',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reports', to='userapp.mentorsession'),
        ),
    ]
