# Generated by Django 5.2.4 on 2025-07-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_mentorreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorreport',
            unique_together=set(),
        ),
    ]
