# Generated by Django 5.2.4 on 2025-07-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_mentorreport_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='focusbuddysession',
            index=models.Index(fields=['creator_id', 'status'], name='userapp_foc_creator_745480_idx'),
        ),
        migrations.AddIndex(
            model_name='focusbuddysession',
            index=models.Index(fields=['status'], name='userapp_foc_status_0313fa_idx'),
        ),
        migrations.AddIndex(
            model_name='focusbuddysession',
            index=models.Index(fields=['session_type'], name='userapp_foc_session_4ae9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['user', 'date'], name='userapp_jou_user_id_c8a44f_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['is_blocked'], name='userapp_jou_is_bloc_1369b9_idx'),
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['is_approved', 'approval_status', 'is_available'], name='userapp_men_is_appr_e31889_idx'),
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['expertise_level'], name='userapp_men_experti_a446c7_idx'),
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['hourly_rate'], name='userapp_men_hourly__1b7bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['rating'], name='userapp_men_rating_36a4db_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentor', 'scheduled_date', 'scheduled_time'], name='userapp_men_mentor__0c58a8_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['student', 'scheduled_date'], name='userapp_men_student_6a6a94_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['status'], name='userapp_men_status_c5659e_idx'),
        ),
    ]
